caila:
  accessToken: 8a3a0439-4a5a-4580-b7e4-886612cbc2b6
  confidenceThreshold: 0.3

connection:
  mode: polling
  accessToken: 8a3a0439-4a5a-4580-b7e4-886612cbc2b6

bot:
  onErrorReply: "Кажется, что-то сломалось. Давайте попробуем ещё раз."